### ISSUE TITLE
bug: giveaway end bug

### ISSUE THREAD

**Issue by soudblox** [yagpdb-cc/yagpdb-cc#133]
When trying to end a giveaway from another channel it will error, but if you end the giveaway the same place where the giveaway is done, it will end.

**To Reproduce:**
1. Make a giveaway in x channel
2. End it from another channel

**Expected behavior:**

The giveaway will end

**Screenshots:**

![image](https://user-images.githubusercontent.com/73058244/103148913-62505e00-4797-11eb-8ea8-f0e57433c282.png)

**Comment by Olde7325** [comment]
Which version are you using? I'll look into working on a fix, if needed.

**Comment by Olde7325** [comment]
Looks like kind-of expected behavior to me, as the bot will instantly announce the winner(s), thus it being more sensible to end the giveaway in the channel it also takes place in.
You are right, the error handling could be done a bit better instead of letting the command error out, I could however imagine that Satty did not thought about people trying to end the giveaway from a different channel.

**Comment by soudblox** [comment]
kek

**Comment by Satty9361** [comment]
Did a small "fix". Apparently sendTemplate does not modify `.Channel` . Kinda unintuitive and I overlooked it. Give me some feedback and the same changes can be applied to the other versions.
