### ISSUE TITLE
Giveaway seems to select only users from certain roles

### ISSUE THREAD

**Issue by savage4618** [yagpdb-cc/yagpdb-cc#232]
I ran 2 giveaways (basic v2) in the last couple days on my server. The first one seems to work no problem, but when the second ran, it chose only users that were a part of a certain role, which included the user that won the first giveaway. 
Now, I understand it is a random draw, but I specified the winners of the second giveaway should total 4 winners, the giveaway ended with only 2 winners selected, and 2 rerolls after that grabbed the same users.
Again, I understand randomness and this COULD happen, but knowing the 2 users that have won are a part of a role that has permission to run the command and are the only 2 users from the role (of a total of 5 users in the role) that entered the giveaway, this seems like SOMETHING is off.

**Comment by jo3-l** [comment]
The most likely explanation for this is that the reaction handler command is only picking up reactions from that role. This could be due to a number of reasons (an example I can think of off the top of my head is hitting the limit of 3 custom commands executed per action).

In any case, due to the fact that you are the only one to report this issue, it's probable that this is a configuration issue of some sort on your end. I'm happy to help debug the issue over Discord through the YAGPDB support server if you'd like.

**Comment by jo3-l** [comment]
This seems to have been resolved over Discord, so I'll close this. If the fix discussed doesn't work, feel free to reopen.
