### ISSUE TITLE
request: suggestions: add role ping option

### ISSUE THREAD

**Issue by Kangy1103** [yagpdb-cc/yagpdb-cc#236]
Hi, would it be possible to add a feature to ping admin when a new suggestion is made?

It would probably have to be an optional thing as some servers would probable be non stop pings

**Comment by LemmeCry** [comment]
When suggestions already have a dedicated channel, an additional ping on top of it seems unnecessary since channel notifications satisfy this already. On top of that, pinging a role on a suggestion would be an easy way to ghost ping by making repetitive suggestions and proceeding to delete them right after. If you still need this nonetheless, you simply need to add `{{$admin_ping := ROLE_ID_HERE}}` and replace line 47 with:
`{{$ID:=sendMessageNoEscapeRetID $Suggestion_Channel (complexMessage "embed" $embed "content" (mentionRoleID $admin_ping))}}`

**Comment by KangyKSLG** [comment]
> When suggestions already have a dedicated channel, an additional ping on top of it seems unnecessary since channel notifications satisfy this already. On top of that, pinging a role on a suggestion would be an easy way to ghost ping by making repetitive suggestions and proceeding to delete them right after. If you still need this nonetheless, you simply need to add `{{$admin_ping := ROLE_ID_HERE}}` with the other configuration variables at the top, and replace line 47 with:
> `{{$ID:=sendMessageNoEscapeRetID $Suggestion_Channel (complexMessage "embed" $embed "content" (mentionRoleID $admin_ping))}}`
>  

Normally I'd agree with you but some of our admin need more of a push to actually check things like this. I appreciate you telling me how to implement it regardless :)
