### ISSUE TITLE
request: HTTP request

### ISSUE THREAD

**Issue by felipedobrinin** [yagpdb-cc/yagpdb-cc#256]
### Description

I am trying to make a command to get an image from an API, but I believe there is no http request method

### Solution

An http request metod 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by BlackWolfWoof** [comment]
I am pretty sure this will never become a feature as this is way too powerful.
What I did is provide my image in the url and add parameters there to manipulate it.
If this will be added tho I won't say no :)

**Comment by LemmeCry** [comment]
That, and taking into consideration the number of servers yag is in, there could potentially be way too many requests at a given instant. Not something for a public bot at this scale —most likely not going to be added.

**Comment by l-zeuch** [comment]
Closing. This is not something the maintainers of this repository have actual jurisdiction over.

There are, however, suggestions on the [support server](https://discord.com/invite/4udtcA5) which do go into a similar direction. 
If you wish to see it implemented, please join the aforementioned server and upvote matching suggestions. Please note though that it is unlikely to be implemented, due to the high risk that goes along with it.
