### ISSUE TITLE
bug: starboard errors if db entry overflows max size

### ISSUE THREAD

**Issue by jo3-l** [yagpdb-cc/yagpdb-cc#27]
## Issue
Starboard works by using a text entry to store key-value pairs in a single database entry, formatted in `messageId:starboardMessageId`. At the time of writing, I considered 100k to be ample space for most server starboards, however, it seems that some servers have come very close to it causing an error when attempting to append data to the entry (which would cause it to go over 100k).

## Error:
```
20 May 20 01:13 UTC - Failed executing template (dur = 185.897545ms): template: CC #15:74:5: executing "CC #15" at <dbSet 0 "starboardMe...>: error calling dbSet: short write
```

## Solution
There's many ways of solving this issue, currently, as a hotfix I've recommended the reporter of the issue to simply clear the database. This is by no means, of course, a permanent fix. One solution would be to create another entry in the code when the last entry is too close to 100k characters, and then looping through a `dbTopEntries` to find the message ID.

I'm also looking for other solutions, this may take a while.

**Comment by Jo3-L** [comment]
Think I finally found a good approach to this that still only uses 1 DB entry but has no noticeable effect for users.
# Solution
*Note: The current code will be migrated to using an sdict, rather than a text entry for storage.*

## Logic
When a post reaches X star emoji reactions, YAGPDB posts it in the starboard channel *only if* it has not reacted on it already. If this condition is met, the following check is done:

*The figure of 2000 key-value pairs was obtained from 40 length for two IDs and then generously rounding to 50. 100k / 50 = 2000.*

If the starboard entry is at 2000 key-value pairs (check is done using `len`) then we find the smallest buffer ID in it. Smaller IDs mean it was created first, so basically we are creating a LRU cache (where recently used = newer starboard messages). We remove this ID from the entry.

**To consider:** What are the performance implications of finding the oldest starboard message?

After these checks are finished, the message is added to the starboard entry, and then YAGPDB *adds the star emoji reaction on it*. If you haven't noticed already, YAGPDB's star emoji reaction basically means that we have posted the message to starboard already.

**Comment by Satty9361** [comment]
There wouldnt be much of a performance issue to look for the smallest id as it would take linear time which otself is of a very small order. If you instead wanted to really implement according to LRU principle though, you would need to maintain a second map containing pairs of message id and updated unix timestamp to check which one was last updated starboard message. This method can be interesting as it lets you extend to multiple entries in the future where you  an have a memory block storing all ids (100 database entries is quite a lot) and if it is not found in the cache then you start finding the message id in the other entries and if found or even otherwise adding both the message id : starboard id entry and message id : unix timestamp entry (while removing the oldest pair from the cache)

**Comment by jo3-l** [comment]
Starboard v2 automatically cleans up the database value if it goes over a predefined limit, so I think we can close this:
https://github.com/yagpdb-cc/yagpdb-cc/blob/bbf02fd1675afa2305e95426b53cb4ec6f944ad1/fun/starboard%20v2/starboardListener.go.tmpl#L51
